# Generated by Django 3.1.2 on 2020-10-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('price', models.CharField(max_length=50, verbose_name='Precio')),
                ('expiration', models.DateField(max_length=4, verbose_name='Fecha de caducidad')),
            ],
        ),
    ]
