# Generated by Django 3.1.2 on 2020-10-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
            ],
        ),
    ]
