# Generated by Django 3.1.2 on 2020-10-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=255, verbose_name='Cantidad')),
                ('product', models.CharField(max_length=255, verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Proveedores')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección de envío')),
                ('date', models.DateField(max_length=4, verbose_name='Fecha de venta')),
            ],
        ),
    ]
