# Generated by Django 3.1.2 on 2020-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0004_auto_20201023_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencias',
            name='brand',
            field=models.CharField(default=0, max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
