# Generated by Django 3.1.2 on 2020-10-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0005_existencias_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencias',
            name='date',
            field=models.DateField(default=0, max_length=4, verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
    ]
