# Generated by Django 3.1.2 on 2020-10-23 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0006_existencias_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencias',
            name='date',
        ),
    ]
