# Generated by Django 3.1.2 on 2020-10-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0008_existencias_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='existencias',
            name='date',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
    ]
