# Generated by Django 3.1.2 on 2020-10-28 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0009_auto_20201023_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='existencias',
            options={'verbose_name': 'Existencia', 'verbose_name_plural': 'Existencias'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
