# Generated by Django 3.1.2 on 2020-11-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0011_remove_existencias_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='expiration',
            field=models.DateField(verbose_name='Fecha de caducidad'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='date',
            field=models.DateField(verbose_name='Fecha de venta'),
        ),
    ]
