# Generated by Django 3.1.2 on 2020-11-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0012_auto_20201109_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencias',
            name='date',
            field=models.DateField(default=0, verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
    ]
