# Generated by Django 3.1.2 on 2020-11-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_existencias_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='date',
        ),
    ]
