# Generated by Django 3.1.2 on 2020-11-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0014_remove_ventas_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencias',
            name='date',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='price',
            field=models.CharField(max_length=10, verbose_name='Precio'),
        ),
    ]
