# Generated by Django 3.1.2 on 2020-11-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_auto_20201109_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='expiration',
        ),
    ]
