# Generated by Django 3.1.2 on 2020-11-10 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0016_remove_productos_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencias',
            name='date',
            field=models.DateTimeField(default=0, verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='existencias',
            name='productos_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmacia.productos', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='expiration',
            field=models.DateTimeField(default=0, verbose_name='Fecha de caducidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='productos_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmacia.productos', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventas',
            name='cliente_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farmacia.clientes', verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
