# Generated by Django 3.1.2 on 2020-11-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0017_auto_20201109_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='cliente_id',
            new_name='clientes_id',
        ),
        migrations.RemoveField(
            model_name='existencias',
            name='date',
        ),
        migrations.AddField(
            model_name='existencias',
            name='entry',
            field=models.CharField(default=0, max_length=4, verbose_name='Fecha de ingreso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='expiration',
            field=models.CharField(max_length=4, verbose_name='Fecha de caducidad'),
        ),
    ]
